Update workflow-validation.yml

diff --git a/.github/workflows/workflow-validation.yml b/.github/workflows/workflow-validation.yml
--- a/.github/workflows/workflow-validation.yml
+++ b/.github/workflows/workflow-validation.yml
@@ -508,6 +508,15 @@ jobs:
               repo: context.repo.repo,
               body: `Provided image does not use the latest version (${process.env['upstream-image-version']}) of [${process.env['upstream-image-repo']}](https://github.com/${process.env['upstream-image-repo']}/releases/latest). Please ensure you are using the latest version of the base image in your Dockerfile.`
             })
+            
+      - name: Debug trivyignore
+        run: |
+          echo "PWD=$(pwd)"
+          ls -la .trivyignore || echo ".trivyignore not found"
+      - name: Show trivyignore contents
+        run: |
+          echo "=== .trivyignore ==="
+          sed -n '1,200p' .trivyignore
 
       - name: Scan
         id: scan
@@ -515,6 +524,8 @@ jobs:
         env:
           TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
           TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
+          TRIVY_LOG_LEVEL: debug
+          TRIVY_IGNOREFILE: .trivyignore
         with:
           image-ref: 509399598587.dkr.ecr.eu-west-2.amazonaws.com/${{ env.ecr-repository }}:${{ env.image-tag }}
           severity: HIGH,CRITICAL
