🩻 Add image scanning and automatic approval logic (#107)
Signed-off-by: Jacob Woffenden <jacob.woffenden@justice.gov.uk>

diff --git a/.github/workflows/workflow-validation.yml b/.github/workflows/workflow-validation.yml
--- a/.github/workflows/workflow-validation.yml
+++ b/.github/workflows/workflow-validation.yml
@@ -153,14 +153,15 @@ jobs:
         with:
           persist-credentials: false
 
+      - name: Clean Actions Runner
+        id: clean_actions_runner
+        uses: ministryofjustice/github-actions/clean-actions-runner@db1a54895bf5fb975c60af47e5a3aab96505ca3e # v18.6.0
+        with:
+          confirm: true
+
       - name: Set Up Container Structure Test
         id: setup_container_structure_test
         uses: ministryofjustice/github-actions/setup-container-structure-test@db1a54895bf5fb975c60af47e5a3aab96505ca3e # v18.6.0
-
-      - name: Fetch Container Structure Test
-        id: fetch_container_structure_test
-        run: |
-          curl --silent --show-error --location https://raw.githubusercontent.com/ministryofjustice/analytical-platform-airflow-github-actions/refs/heads/main/assets/container-structure-test/container-structure-test.yml --output container-structure-test.yml
 
       - name: Download path-filters File
         id: download_path_filters
@@ -193,17 +194,17 @@ jobs:
       - name: Set ECR Repository
         id: set_ecr_repository
         run: |
-          ecrRepositoryRaw=$(yq -e ".dag.repository" "${{ env.workflow-directory }}/workflow.yml")
-          export ecrRepositoryRaw
+          dagRepository=$(yq -e ".dag.repository" "${{ env.workflow-directory }}/workflow.yml")
+          export dagRepository
 
-          ecrRepository=$(echo "${ecrRepositoryRaw}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
+          ecrRepository=$(echo "${dagRepository}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
           export ecrRepository
 
-          imageTag=$(yq -e ".dag.tag" "${{ env.workflow-directory }}/workflow.yml")
-          export imageTag
+          dagTag=$(yq -e ".dag.tag" "${{ env.workflow-directory }}/workflow.yml")
+          export dagTag
 
           echo "ecr-repository=${ecrRepository}" >>"${GITHUB_ENV}"
-          echo "image-tag=${imageTag}" >>"${GITHUB_ENV}"
+          echo "image-tag=${dagTag}" >>"${GITHUB_ENV}"
 
       - name: Check Image Exists
         id: check_image_exists
@@ -228,6 +229,11 @@ jobs:
         run: |
           docker pull "509399598587.dkr.ecr.eu-west-2.amazonaws.com/${{ env.ecr-repository }}:${{ env.image-tag }}"
 
+      - name: Fetch Container Structure Test
+        id: fetch_container_structure_test
+        run: |
+          curl --silent --show-error --location https://raw.githubusercontent.com/ministryofjustice/analytical-platform-airflow-github-actions/refs/heads/main/assets/container-structure-test/container-structure-test.yml --output container-structure-test.yml
+
       - name: Container Structure Test
         id: container_structure_test
         shell: bash
@@ -244,5 +250,205 @@ jobs:
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: 'Container test has failed. Refer to the [User Guide](https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html#configuration-testing) for more information.'
+              body: 'Container test has failed. Refer to the [User Guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html#configuration-testing) for more information.'
+            })
+
+      - name: Generate Trivy Ignore
+        id: generate_trivy_ignore
+        env:
+          GH_TOKEN: ${{ secrets.DATA_PLATFORM_ROBOT_TOKEN }}
+        run: |
+          dagRepository=$(yq -e ".dag.repository" "${{ env.workflow-directory }}/workflow.yml")
+          export dagRepository
+
+          dagTag=$(yq -e ".dag.tag" "${{ env.workflow-directory }}/workflow.yml")
+          export dagTag
+
+          downloadDockerfile=$(gh api "repos/${dagRepository}/contents/Dockerfile?ref=${dagTag}" 2>/dev/null || true)
+          export downloadDockerfile
+
+          downloadDockerfileStatus=$(jq -r '.status' <<< "${downloadDockerfile}")
+          export downloadDockerfileStatus
+
+          if [[ "${downloadDockerfileStatus}" == "null" ]]; then
+            jq -r '.content' <<< "${downloadDockerfile}" | base64 --decode > Dockerfile
+          elif [[ "${downloadDockerfileStatus}" == "404" ]]; then
+            echo "Dockerfile not found"
+            exit 1
+          else
+            echo "Error downloading Dockerfile"
+            exit 1
+          fi
+
+          downloadTrivyignore=$(gh api "repos/${dagRepository}/contents/.trivyignore?ref=${dagTag}" 2>/dev/null || true)
+          export downloadTrivyignore
+
+          downloadTrivyignoreStatus=$(jq -r '.status' <<< "${downloadTrivyignore}")
+          export downloadTrivyignoreStatus
+
+          if [[ "${downloadTrivyignoreStatus}" == "null" ]]; then
+            jq -r '.content' <<< "${downloadTrivyignore}" | base64 --decode > .trivyignore
+          elif [[ "${downloadTrivyignoreStatus}" == "404" ]]; then
+            echo ".trivyignore not found" # It's OK if we don't find one, it means the user might not have created one yet
+          else
+            echo "Error downloading .trivyignore"
+            exit 1
+          fi
+
+          imageName=$(grep "^FROM" Dockerfile | cut -d' ' -f2 | cut -d':' -f1 | cut -d'@' -f1)
+          export imageName
+
+          imageVersion=$(grep "^FROM" Dockerfile | cut -d':' -f2 | cut -d'@' -f1)
+          export imageVersion
+
+          imageRepo=${imageName#ghcr.io/}
+
+          curl --silent --show-error --location "https://raw.githubusercontent.com/${imageRepo}/refs/tags/${imageVersion}/.trivyignore" --output "runtime-trivyignore"
+
+          if [[ ! -f .trivyignore ]]; then
+            mv "runtime-trivyignore" .trivyignore
+          else
+            cat "runtime-trivyignore" >> .trivyignore
+          fi
+
+      - name: Scan
+        id: scan
+        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
+        env:
+          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
+          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
+        with:
+          image-ref: 509399598587.dkr.ecr.eu-west-2.amazonaws.com/${{ env.ecr-repository }}:${{ env.image-tag }}
+          severity: HIGH,CRITICAL
+          ignore-unfixed: true
+          vuln-type: library
+          timeout: 10m0s
+          exit-code: 1
+
+      - name: Comment on Scan Failure
+        id: comment_on_scan_failure
+        if: failure() && steps.scan.outcome == 'failure'
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: 'Container scan has failed. Refer to the [User Guide](https://user-guidance.analytical-platform.service.justice.gov.uk/services/airflow/index.html#vulnerability-scanning) for more information.'
+            })
+
+  automatic-approval-gate:
+    if: ${{ needs.detect-changes.outputs.workflows != '[]' }}
+    needs: [detect-changes, workflow-validation, image-check]
+    name: 🛂 Automatic Approval Gate
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        workflow: ${{ fromJson(needs.detect-changes.outputs.workflows) }}
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          persist-credentials: false
+
+      - name: Set Up UV
+        id: setup_uv
+        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
+        with:
+          version: "latest"
+          python-version: "3.11"
+
+      - name: Install Requirements
+        id: install_requirements
+        run: |
+          uv pip install --requirements requirements.txt
+
+      - name: Download path-filters File
+        id: download_path_filters
+        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
+        with:
+          name: workflows-path-filter
+          path: .github/path-filter
+
+      - name: Set Workflow Directory
+        id: set_workflow_directory
+        env:
+          WORKFLOW: ${{ matrix.workflow }}
+        run: |
+          workflowDirectory=$(yq -e ".${WORKFLOW}" .github/path-filter/workflows.yml | sed 's/.\{3\}$//')
+          export workflowDirectory
+
+          echo "workflow-directory=${workflowDirectory}" >>"${GITHUB_ENV}"
+
+      - name: Automatic Approval Check
+        id: automatic_approval_check
+        env:
+          GH_TOKEN: ${{ secrets.DATA_PLATFORM_ROBOT_TOKEN }}
+        run: |
+          git fetch origin main
+
+          changed_files=$(git diff --name-only origin/main)
+          changed_files_status=$(git diff --name-status origin/main | awk '{ print $1 }')
+
+          echo "${changed_files}"
+          echo "${changed_files_status}"
+
+          # Default to true
+          eligible="true"
+
+          # Check if any files were added or deleted
+          for status in ${changed_files_status}; do
+            if [[ ${status} != "M" ]]; then
+              echo "File status ${status} detected, not eligible for automatic approval"
+              exit 0
+            fi
+          done
+
+          # Check if the workflow file has been modified, and in what way
+          if [[ $(git diff --name-status origin/main ${{ env.workflow-directory }}/workflow.yml | awk '{ print $1 }') == "M" ]]; then
+            echo "Workflow file ${{ env.workflow-directory }}/workflow.yml has been modified, eligible for automatic approval depending on changes"
+            gh api "repos/${{ github.repository }}/contents/${{ env.workflow-directory }}/workflow.yml?ref=main" --jq '.content' | base64 --decode > "${{ env.workflow-directory }}/workflow-main.yml"
+
+            if [[ $(python scripts/yaml_diff/main.py "${{ env.workflow-directory }}/workflow-main.yml" "${{ env.workflow-directory }}/workflow.yml") == "Only dag.tag has changed" ]]; then
+              echo "Only dag.tag has changed, eligible for automatic approval"
+            else
+              echo "Workflow file ${{ env.workflow-directory }}/workflow.yml has been modified, not eligible for automatic approval"
+              exit 0
+            fi
+          fi
+
+          # Check if any files outside the specified path were changed
+          for file in ${changed_files}; do
+            if [[ ${file} != "environments/development/*" ]]; then
+              echo "File ${file} changed outside the specified path, not eligible for automatic approval"
+              exit 0
+            fi
+          done
+
+          if [[ ${eligible} == "true" ]]; then
+            echo "Eligible for automatic approval"
+          else
+            echo "Not eligible for automatic approval"
+          fi
+
+          echo "eligible=${eligible}" >>"${GITHUB_OUTPUT}"
+
+      - name: Automatic Approval
+        if: steps.automatic_approval_check.outputs.eligible == 'true'
+        id: automatic_approval
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
+        with:
+          github-token: ${{ secrets.DATA_PLATFORM_ROBOT_TOKEN }}
+          script: |
+            github.rest.pulls.createReview({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              pull_number: context.payload.pull_request.number,
+              body: 'Automatic approval requirements satisfied.',
+              event: 'APPROVE'
             })
